# ruff: noqa: F401,F403
from sklearn import (
    cluster,
    covariance,
    decomposition,
    discriminant_analysis,
    ensemble,
    feature_selection,
    gaussian_process,
    isotonic,
    kernel_ridge,
    linear_model,
    manifold,
    mixture,
    naive_bayes,
    neighbors,
    neural_network,
    semi_supervised,
    svm,
    tree,
)
from sklearn.calibration import CalibratedClassifierCV
from sklearn.cross_decomposition import PLSRegression

from clml.constants import *  # noqa: F403
from clml.methods._factories import (
    GBM_COMPARISONS_CLASSIFIER,
    GBM_COMPARISONS_REGRESSOR,
    _catboost_classifier,
    _catboost_regressor,
    _ebm_classifier,
    _ebm_regressor,
    _lightgbm_classifier,
    _lightgbm_regressor,
    _ngboost_regressor,
    _rfe_logistic,
    _rfecv_logistic,
    _river_logistic_regression,
    _select_from_l1_linear_svc,
    _select_k_best_f_classif,
    _select_k_best_mutual_info,
    _stacking_classifier,
    _stacking_regressor,
    _umap,
    _voting_classifier,
    _voting_regressor,
    _xgboost_classifier,
    _xgboost_regressor,
)
from clml.methods._spaces import (
    _cluster_space,
    _component_space,
    _forest_space,
    _glm_alpha_space,
    _gradient_boosting_space,
    _huber_space,
    _linear_svc_space,
    _lle_space,
    _neighbors_space,
    _nu_svc_space,
    _quantile_space,
    _regularization_space,
    _svc_space,
    _tree_space,
    _tsne_space,
    _tweedie_space,
    _umap_space,
)
from clml.methods._types import MethodSpec
