USER_GUIDE_COVERAGE = {
    "Supervised learning": [
        "Linear models",
        "Discriminant analysis",
        "Kernel ridge regression",
        "Support Vector Machines",
        "Stochastic Gradient Descent",
        "Nearest Neighbors",
        "Gaussian Processes",
        "Cross decomposition",
        "Naive Bayes",
        "Decision Trees",
        "Ensembles",
        "Semi-supervised learning",
        "Isotonic regression",
        "Probability calibration",
        "Neural network models",
        "Feature selection",
    ],
    "Unsupervised learning": [
        "Gaussian mixture models",
        "Manifold learning",
        "Clustering",
        "Matrix factorization",
        "Covariance estimation",
        "Novelty and outlier detection",
        "Density estimation",
    ],
    "Model selection and evaluation": [
        "Train/test evaluation",
        "Optuna hyperparameter optimization",
        "Classification, regression, clustering, and anomaly metrics",
    ],
    "Extended methods": [
        "XGBoost",
        "LightGBM",
        "CatBoost",
        "SciPy linear programming",
        "SciPy nonlinear constrained optimization",
        "statsmodels",
        "statsmodels time series",
        "imbalanced-learn",
        "category-encoders",
        "CVXPY",
        "lifelines",
        "interpret",
        "UMAP",
        "NGBoost",
        "River",
    ],
    "Dataset transformations": [
        "Pipeline composition",
        "Scaling",
        "Non-negative scaling for count-like estimators",
        "Dimensionality reduction projections",
    ],
}
